# Generated by Django 5.0 on 2024-06-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('belongs_to_collection', models.BooleanField(default=False)),
                ('origin_country', models.CharField(max_length=20)),
                ('runtime', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
    ]
