# Generated by Django 5.0 on 2024-06-07 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('belongs_to_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.collection')),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
    ]
