# Generated by Django 5.0 on 2024-07-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('imdb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('original_title', models.CharField(blank=True, max_length=100, null=True)),
                ('backdrop_url', models.URLField(blank=True, null=True)),
                ('belongs_to_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.collection')),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('ratings_id', models.AutoField(primary_key=True, serialize=False)),
                ('tmdb_popularity', models.FloatField(blank=True, null=True)),
                ('tmdb_vote_average', models.FloatField(blank=True, null=True)),
                ('tmdb_vote_count', models.IntegerField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imdb_vote_count', models.DecimalField(decimal_places=0, max_digits=15)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
            ],
        ),
    ]
