# Generated by Django 5.0 on 2024-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='imdb_rating',
        ),
        migrations.AddField(
            model_name='ratings',
            name='imdb_vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='imdb_vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
