# Generated by Django 5.0 on 2024-06-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_movie_belongs_to_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='origin_country',
        ),
    ]
