# Generated by Django 5.0 on 2024-07-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ratings_imdb_rating_ratings_imdb_vote_average_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='imdb_vote_average',
            new_name='imdb_rating',
        ),
    ]
